# Generated by Django 4.1.3 on 2023-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ciphertext_algo_id_alter_ciphertext_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciphertext',
            name='algo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
